import Head from 'next/head'
import React from 'react'
import Header from '../components/Header'
import Nav from '../components/Nav'

export default function Home(): React.ReactElement {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Nav */}
      <Nav />

      {/* Results */}
    </div>
  )
}
